#!/usr/bin/env bash
source $(cli loader)
source /dev/stdin < <(cli::import vscs .dir)
source /dev/stdin < <(cli::import cli_util)

help() (
util::unindent << EOF
    Command
        ${CLI_PATH} : Install a version of Visual Studio Code Server.

    Arguments
        --commit -c     [Required]  : Commit to install. (e.g. d2e414d9e4239a252d1ab117bd7067f125afd80a)
        --build -b      [Required]  : Server build flavor. Allowed values: stable,
                                        insiders. Default: stable.
        --os-arch       [Required]  : Target operating system. Allowed values: darwin, linux-x64, 
                                        linux-armhf, linux-arm64. Default: linux-x64. 'darwin' is macos.
        --architecture  [Required]  : Target architecture. Default: x64.
        --verbose -v                : Enable verbose logging during file download.

    Global Arguments
        --help -h                   : Show this message and exit.
        --run-as                    : User account under which to execute the command.

    Debug Arguments
        --debug -x                  : Echo the commands being executed.
        --dry-run                   : Show the commands that would be run.
EOF
)

main() {
    local server_dir
    local commit_dir
    local url
    local wget_verbosity=

    vscs::declare_dirs
    : ${server_dir:?}
    : ${commit_dir:?}

    local url=${VSCS_HOST}/commit:${arg_commit}/server-${arg_os_arch}

    case "${arg_build}" in
        stable) url="${url}/stable" ;;
        *) url="${url}/insider" ;;
    esac

    if [[ ! $arg_verbose == 'true' ]]; then
        wget_verbosity='-nv'
    fi

    util::unindent << EOF | util::source
    mkdir -p ${commit_dir}
    wget ${wget_verbosity} ${url} -O ${VSCS_TARGZC_TEMP}
    tar -x -f ${VSCS_TARGZC_TEMP} --strip-components 1 -C ${commit_dir}
    rm ${VSCS_TARGZC_TEMP}
EOF
}

cli::load "$@"