#!/usr/bin/env bash
source $(cli loader)
source /dev/stdin < <(cli::import vscs .dir)
source /dev/stdin < <(cli::import cli_util)

help() (
    util::unindent << EOF
    Command
        vscs ls : Lists installed versions of Visual Studio Code Server.

    Arguments
        --build -b       [Required] : Server build flavor. Allowed values: stable,
                                        insiders. Default: stable.
        --dir                       : Echo the directory hosting the servers.

    Global Arguments
        --help -h                   : Show this message and exit.
        --run-as                    : User account under which to execute the command.
        --verbose -v                : Enable verbose logging during file download.

    Debug Arguments
        --debug -x                  : Echo the commands being executed.
        --dry-run                   : Show the commands that would be run.
EOF
)

main() {
    local server_dir
    local bin_dir

    vscs::declare_server_dirs
    : ${server_dir:?}

    bin_dir="${server_dir}/bin/"
    if [[ "${arg_dir}" == true ]]; then
        echo "${bin_dir}"
        exit
    fi

    for entry in ${bin_dir}/*; do
        echo "${entry##*/}"
    done
}

cli::load "$@"