#!/usr/bin/env bash
source $(cli loader)
source /dev/stdin < <(cli::import vscs .dir)
source /dev/stdin < <(cli::import cli_util)

help() (
util::unindent << EOF
    Command
        ${CLI_COMMAND} : Yield the pid of a running Visual Studio Code Server.

    Arguments
        --commit -c     [required]  : Commit of running server.
        --build -b      [Required]  : Server build flavor. Allowed values: stable,
                                        insiders. Default: stable.

    Global Arguments
        --help -h                   : Show this message and exit.
        --run-as                    : User account under which to execute the command.

    Debug Arguments
        --debug -x                  : Echo the commands being executed.
        --dry-run                   : Show the commands that would be run.
        --tokenize-help             : Tokenize help
        --parse-help                : Parse help
EOF
)

main() {
    local server_dir
    local commit_dir

    vscs::declare_dirs
    : ${server_dir:?}
    : ${commit_dir:?}

    util::unindent << EOF | util::source
    read pid reply < <(ps ax | grep "${commit_dir}/server.sh" | grep -v grep)
    echo "\${pid}"
EOF
}

cli::load "$@"