#!/usr/bin/env bash
source $(cli loader ---exports)
source /dev/stdin < <(cli::import vscs .dir)
source /dev/stdin < <(cli::import cli_util)

help() (
util::unindent << EOF
    Command
        ${CLI_COMMAND} : Start the server.

    Arguments
        --commit -c  [Required] : Commit to install. (e.g. d2e414d9e4239a252d1ab117bd7067f125afd80a)
        --build -b   [Required] : Build flavor. Allowed values: stable, insiders. 
                                    Default: stable.

    Global Arguments
        --help -h               : Show this message and exit.
        --run-as                : User account under which to execute the command.

    Debug Arguments
        --debug -x              : Echo the commands being executed.
        --dry-run               : Show the commands that would be run.
        --tokenize-help         : Tokenize help
        --parse-help            : Parse help
EOF
)

main() {
    vscs::declare_dirs
    : ${server_dir:?}
    : ${commit_dir:?}

    util::unindent << EOF | util::source
    ${server_dir}/bin/${arg_commit}/server.sh \
        --host=127.0.0.1 \
        --enable-remote-auto-shutdown \
        --port=0 \
        &> ${server_dir}/.${arg_commit}.log \
        < /dev/null &
EOF
}

cli::main "$@"