#!/usr/bin/env bash
source $(cli loader ---exports)
source /dev/stdin < <(cli::import vscs .dir)
source /dev/stdin < <(cli::import cli_util)

help() (
util::unindent << EOF
    Command
        ${CLI_COMMAND} : Remove a version of Visual Studio Code Server.

    Arguments
        --commit -c     [Required]  : Commit to uninstall. (e.g. d2e414d9e4239a252d1ab117bd7067f125afd80a)
        --build -b      [Required]  : Server build flavor. Allowed values: stable,
                                        insiders. Default: stable.
        --verbose -v                : Enable verbose logging during file download.

    Global Arguments
        --help -h                   : Show this message and exit.

    Debug Arguments
        --debug -x                  : Echo the commands being executed.
        --dry-run                   : Show the commands that would be run.
EOF
)

main() {
    local server_dir
    local commit_dir

    vscs::declare_dirs
    : ${server_dir:?}
    : ${commit_dir:?}

    util::unindent << EOF | util::source
    rm -r ${commit_dir}
EOF
}

cli::main "$@"